# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_uUU3HPO19ad8p1UfRGEO6XRjLeZrAx6
"""

print("Hello Word")